name: Pull Latest Courses
on:
  schedule:
    - cron: '4 4 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install -r util/requirements.txt
      - name: Run parser script
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
        run: python util/sync_sheet.py

      - name: Commit and Push JSON
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add catalog.json
          git commit -m "Update data from Google Sheets" || echo "No changes to commit"
          git push


